CREATE TABLE IF NOT EXISTS CHBS_ROLEINFO (
	ROLEID VARCHAR(20) PRIMARY KEY, 
	ROLEDESC VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHBS_SLOTINFO (
	SLOTID INT PRIMARY KEY, 
    SLOTTIME VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHBS_MEETINGTYPES (
    MEETID INT AUTO_INCREMENT PRIMARY KEY,
    MEETNAME VARCHAR(100) NOT NULL,
    MEETDESC VARCHAR(100) NOT NULL
);

-- ACCESS CONTROL & USERS
CREATE TABLE IF NOT EXISTS CHBS_USERINFO (
    EMPLOYEECODE VARCHAR(7) PRIMARY KEY,
    EMPLOYEENAME VARCHAR(100) NOT NULL,
    PASSWRD VARCHAR(255) NOT NULL, 
    STATUS ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    ROLEID VARCHAR(20) NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES CHBS_ROLEINFO (ROLEID)
);

CREATE TABLE IF NOT EXISTS CHBS_PA (
    PA_EMPCODE VARCHAR(7) PRIMARY KEY,
    PA_NAME VARCHAR(100) NOT NULL,
    PASSWRD VARCHAR(255) NOT NULL, 
    STATUS ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE'
);

-- FACILITY & HOLIDAYS
CREATE TABLE IF NOT EXISTS CHBS_HALLS (
    HALLID INT AUTO_INCREMENT PRIMARY KEY, 
    BUILDNAME VARCHAR(100) NOT NULL,
    HALLNAME VARCHAR(100) NOT NULL,
    HALLCODE VARCHAR(20) NOT NULL UNIQUE,
    ISAVAILABLE TINYINT(1) DEFAULT 1,
    ISDIRECTORHALL TINYINT(1) DEFAULT 0, 
    DISABLED_FROM DATE NULL,
    DISABLED_TO DATE NULL
);

CREATE TABLE IF NOT EXISTS CHBS_HOLIDAYS (
    HOLIDAYDATE DATE PRIMARY KEY,
    HOLIDAYNAME VARCHAR(100) NOT NULL,
    HOLIDAYTYPE VARCHAR(20) DEFAULT 'NATIONAL',
    ISRECURRING BIT DEFAULT 0
);

-- TRANSACTIONAL CORE
CREATE TABLE IF NOT EXISTS CHBS_BOOKINGINFO (
    BOOKINGID VARCHAR(50) PRIMARY KEY,
    HALLID INT NOT NULL,
    BOOKEDBY VARCHAR(7) NOT NULL,
    ONBEHALFOF VARCHAR(7) NULL,
    STARTSLOT INT NOT NULL,
    ENDSLOT INT NOT NULL,
    BOOKINGDATE DATE NOT NULL,
    BOOKINGSTATUS ENUM('CONFIRMED', 'PENDING', 'CANCELLED', 'REJECTED') DEFAULT 'CONFIRMED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BI_HALL FOREIGN KEY (HALLID) REFERENCES CHBS_HALLS (HALLID),
    CONSTRAINT FK_BI_SLOT_START FOREIGN KEY (STARTSLOT) REFERENCES CHBS_SLOTINFO (SLOTID),
    CONSTRAINT FK_BI_SLOT_END FOREIGN KEY (ENDSLOT) REFERENCES CHBS_SLOTINFO (SLOTID)
);

CREATE TABLE IF NOT EXISTS CHBS_MEETINFO (
    BOOKINGID VARCHAR(50) PRIMARY KEY,
    MEETTITLE VARCHAR(150) NOT NULL,
    MEETTYPE INT NOT NULL,
    LINKREQUIRED ENUM('YES', 'NO') DEFAULT 'NO',
    CONSTRAINT FK_MI_BOOKING FOREIGN KEY (BOOKINGID) REFERENCES CHBS_BOOKINGINFO (BOOKINGID),
    CONSTRAINT FK_MI_MTYP FOREIGN KEY (MEETTYPE) REFERENCES CHBS_MEETINGTYPES (MEETID)
);

-- HISTORY TABLES MOVE OLD BOOKINGS
CREATE TABLE IF NOT EXISTS CHBS_BK_HIST LIKE CHBS_BOOKINGINFO;
CREATE TABLE IF NOT EXISTS CHBS_MT_HIST LIKE CHBS_MEETINFO;

