DELIMITER //

-- AUTHENTICATION
CREATE PROCEDURE CHSP_USR_LOG(IN p_Code VARCHAR(7))
BEGIN
    SELECT EMPLOYEECODE, EMPLOYEENAME, PASSWRD, ROLEID, STATUS 
    FROM CHBS_USERINFO WHERE EMPLOYEECODE = p_Code AND STATUS = 'ACTIVE';
END //

CREATE PROCEDURE CHSP_PA_LOG(IN p_Code VARCHAR(7))
BEGIN
    SELECT PA_EMPCODE, PA_NAME, PASSWRD, STATUS 
    FROM CHBS_PA WHERE PA_EMPCODE = p_Code AND STATUS = 'ACTIVE';
END //

CREATE PROCEDURE CHSP_USR_ALL()
BEGIN
    SELECT EMPLOYEECODE, EMPLOYEENAME, ROLEID FROM CHBS_USERINFO 
    WHERE STATUS = 'ACTIVE' ORDER BY EMPLOYEENAME ASC;
END //

-- HALL MANAGEMENT
CREATE PROCEDURE CHSP_HAL_AMAD(IN p_HName VARCHAR(100), IN p_BName VARCHAR(100), IN p_HCode VARCHAR(10), IN p_isDir TINYINT(1))
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT 'ERROR' AS Status;
    INSERT INTO CHBS_HALLS (BUILDNAME, HALLNAME, HALLCODE, ISDIRECTORHALL) 
    VALUES (p_BName, p_HName, p_HCode, p_isDir);
    SELECT LAST_INSERT_ID() AS CreatedID, 'SUCCESS' AS Status;
END //

CREATE PROCEDURE CHSP_HAL_EDT(IN p_HID INT, IN p_HName VARCHAR(100), IN p_BName VARCHAR(100), IN p_isDir TINYINT(1))
BEGIN
    UPDATE CHBS_HALLS SET HALLNAME = p_HName, BUILDNAME = p_BName, ISDIRECTORHALL = p_isDir WHERE HALLID = p_HID;
    SELECT 'SUCCESS' AS Status;
END //

CREATE PROCEDURE CHSP_HAL_DIS(IN p_HID INT, IN p_From DATE, IN p_To DATE)
BEGIN
    UPDATE CHBS_HALLS SET ISAVAILABLE = 0, DISABLED_FROM = p_From, DISABLED_TO = p_To WHERE HALLID = p_HID;
    SELECT 'SUCCESS' AS Status;
END //

CREATE PROCEDURE CHSP_GET_HALB(IN p_MDate DATE)
BEGIN
    SELECT 
        HALLID, 
        HALLNAME, 
        BUILDNAME, 
        ISDIRECTORHALL 
    FROM CHBS_HALLS
    WHERE ISAVAILABLE = 1 
       OR (
           p_MDate NOT BETWEEN COALESCE(DISABLED_FROM, '1900-01-01') 
                           AND COALESCE(DISABLED_TO, '1900-01-01')
       );
END //



-- MEET TYPE  MANAGEMENT
CREATE PROCEDURE CHSP_MTYP_ADD(IN p_MName VARCHAR(100), IN p_MDesc VARCHAR(100))
BEGIN
    INSERT INTO CHBS_MEETINGTYPES (MEETNAME, MEETDESC) VALUES (p_MName, p_MDesc);
    SELECT LAST_INSERT_ID() AS CreatedID, 'SUCCESS' AS Status;
END //

CREATE PROCEDURE CHSP_MTYP_EDT(IN p_MID INT, IN p_MName VARCHAR(100), IN p_MDesc VARCHAR(100))
BEGIN
    UPDATE CHBS_MEETINGTYPES SET MEETNAME = p_MName, MEETDESC = p_MDesc WHERE MEETID = p_MID;
    SELECT 'SUCCESS' AS Status;
END //

CREATE PROCEDURE CHSP_BK_HAL(
    IN p_HID INT, IN p_By VARCHAR(7), IN p_Behalf VARCHAR(7),
    IN p_Ttl VARCHAR(150), IN p_Typ INT, IN p_Start INT, 
    IN p_End INT, IN p_MeetDate DATE, IN p_Lnk VARCHAR(3)
)
BEGIN
    DECLARE n_uuid VARCHAR(50) DEFAULT UUID();
    DECLARE conflict_count, is_holiday, v_isDir INT DEFAULT 0;
    DECLARE final_status ENUM('CONFIRMED', 'PENDING', 'CANCELLED', 'REJECTED');
    SELECT COUNT(*) INTO is_holiday FROM CHBS_HOLIDAYS WHERE HOLIDAYDATE = p_MeetDate;
    IF is_holiday > 0 THEN
        SELECT 'HOLIDAY_RESTRICTION' AS Status;
    ELSE
        BEGIN
            DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; SELECT 'ERROR' AS Status; END;
            START TRANSACTION;
            SELECT ISDIRECTORHALL INTO v_isDir FROM CHBS_HALLS WHERE HALLID = p_HID;
            SELECT COUNT(*) INTO conflict_count FROM CHBS_BOOKINGINFO
            WHERE HALLID = p_HID AND BOOKINGDATE = p_MeetDate AND BOOKINGSTATUS IN ('CONFIRMED', 'PENDING')
              AND (STARTSLOT < p_End AND ENDSLOT > p_Start) FOR UPDATE;

            IF v_isDir = 1 OR conflict_count > 0 THEN SET final_status = 'PENDING';
            ELSE SET final_status = 'CONFIRMED';
            END IF;

            INSERT INTO CHBS_BOOKINGINFO (BOOKINGID, HALLID, BOOKEDBY, ONBEHALFOF, STARTSLOT, ENDSLOT, BOOKINGDATE, BOOKINGSTATUS)
            VALUES (n_uuid, p_HID, p_By, p_Behalf, p_Start, p_End, p_MeetDate, final_status);
            INSERT INTO CHBS_MEETINFO (BOOKINGID, MEETTITLE, MEETTYPE, LINKREQUIRED)
            VALUES (n_uuid, p_Ttl, p_Typ, p_Lnk);
            COMMIT;
            SELECT n_uuid AS BookingID, final_status AS Status;
        END;
    END IF;
END //

--  ADMIN APPROVALS
CREATE PROCEDURE CHSP_AD_DECD(IN p_BKID VARCHAR(50), IN p_Stat VARCHAR(20))
BEGIN
    DECLARE n_HID INT;
    DECLARE n_Date DATE;
    DECLARE n_Start, n_End, conflict, is_holiday INT DEFAULT 0;

    IF p_Stat NOT IN ('CONFIRMED', 'REJECTED') THEN
        SELECT 'INVALID_STATUS' AS Status;
    ELSE
        SELECT HALLID, BOOKINGDATE, STARTSLOT, ENDSLOT INTO n_HID, n_Date, n_Start, n_End 
        FROM CHBS_BOOKINGINFO WHERE BOOKINGID = p_BKID AND BOOKINGSTATUS = 'PENDING';

        IF n_HID IS NULL THEN
            SELECT 'NOT_FOUND_OR_NOT_PENDING' AS Status;
        ELSE
            SELECT COUNT(*) INTO is_holiday FROM CHBS_HOLIDAYS WHERE HOLIDAYDATE = n_Date;

            IF is_holiday > 0 AND p_Stat = 'CONFIRMED' THEN
                SELECT 'CANNOT_APPROVE_ON_HOLIDAY' AS Status;
            ELSE
                START TRANSACTION;
                IF p_Stat = 'CONFIRMED' THEN
                    SELECT COUNT(*) INTO conflict FROM CHBS_BOOKINGINFO
                    WHERE HALLID = n_HID AND BOOKINGDATE = n_Date AND BOOKINGSTATUS = 'CONFIRMED'
                      AND BOOKINGID <> p_BKID AND (STARTSLOT < n_End AND ENDSLOT > n_Start) FOR UPDATE;
                END IF;

                IF conflict > 0 THEN
                    ROLLBACK; SELECT 'CONFLICT_EXISTS' AS Status;
                ELSE
                    UPDATE CHBS_BOOKINGINFO SET BOOKINGSTATUS = p_Stat WHERE BOOKINGID = p_BKID;
                    COMMIT; SELECT 'SUCCESS' AS Status;
                END IF;
            END IF;
        END IF;
    END IF;
END //



-- AUTOMATED MAINTENANCE (moving  old booking data to this table + Auto-enable hall)
CREATE PROCEDURE CHSP_AD_MAINTENANCE_AUTO()
BEGIN
    START TRANSACTION;
    -- Safe Archive (Prevents PK Violation)
    INSERT INTO CHBS_BK_HIST 
    SELECT * FROM CHBS_BOOKINGINFO B
    WHERE B.BOOKINGDATE < DATE_SUB(CURDATE(), INTERVAL 30 DAY) 
      AND B.BOOKINGSTATUS IN ('CANCELLED', 'REJECTED')
      AND NOT EXISTS (SELECT 1 FROM CHBS_BK_HIST BH WHERE BH.BOOKINGID = B.BOOKINGID);
    
    INSERT INTO CHBS_MT_HIST 
    SELECT M.* FROM CHBS_MEETINFO M JOIN CHBS_BK_HIST H ON M.BOOKINGID = H.BOOKINGID
    WHERE NOT EXISTS (SELECT 1 FROM CHBS_MT_HIST MH WHERE MH.BOOKINGID = M.BOOKINGID);
    
    DELETE FROM CHBS_MEETINFO WHERE BOOKINGID IN (SELECT BOOKINGID FROM CHBS_BK_HIST);
    DELETE FROM CHBS_BOOKINGINFO WHERE BOOKINGID IN (SELECT BOOKINGID FROM CHBS_BK_HIST);
    
    -- Auto-Enable Halls
    UPDATE CHBS_HALLS SET ISAVAILABLE = 1, DISABLED_FROM = NULL, DISABLED_TO = NULL 
    WHERE ISAVAILABLE = 0 AND DISABLED_TO < CURDATE();
    COMMIT;
END //

-- DASHBOARDS
CREATE PROCEDURE CHSP_BK_DSH_LIVE(IN p_EmpCode VARCHAR(7))
BEGIN
    SELECT * FROM VW_CHBS_DASHBOARD
    WHERE BOOKEDBY = p_EmpCode OR ONBEHALFOF = p_EmpCode
    ORDER BY MeetDate DESC;
END //

CREATE PROCEDURE CHSP_BK_DSH_HIST(IN p_EmpCode VARCHAR(7))
BEGIN
    SELECT * FROM VW_CHBS_HISTORY
    WHERE BOOKEDBY = p_EmpCode OR ONBEHALFOF = p_EmpCode
    ORDER BY MeetDate DESC;
END //

-- LOOKUP / DROPDOWN DATA
CREATE PROCEDURE CHSP_HAL_ALL()
BEGIN
    SELECT HALLID, HALLNAME, BUILDNAME, HALLCODE, ISAVAILABLE, ISDIRECTORHALL
    FROM CHBS_HALLS ORDER BY BUILDNAME, HALLNAME;
END //

CREATE PROCEDURE CHSP_SLT_ALL()
BEGIN
    SELECT SLOTID, SLOTTIME FROM CHBS_SLOTINFO ORDER BY SLOTID;
END //

CREATE PROCEDURE CHSP_MTYP_ALL()
BEGIN
    SELECT MEETID, MEETNAME, MEETDESC FROM CHBS_MEETINGTYPES ORDER BY MEETNAME;
END //

-- ADMIN QUEUE
CREATE PROCEDURE CHSP_AD_PEND()
BEGIN
    SELECT 
        B.BOOKINGID, B.BOOKINGDATE AS MeetDate, B.CREATED_AT AS SubmittedAt,
        H.HALLNAME, H.BUILDNAME, H.ISDIRECTORHALL,
        CONCAT(S1.SLOTTIME, ' to ', S2.SLOTTIME) AS TIME_RANGE,
        M.MEETTITLE, MT.MEETNAME AS MeetType,
        B.BOOKEDBY, B.ONBEHALFOF
    FROM CHBS_BOOKINGINFO B
    JOIN CHBS_HALLS H ON B.HALLID = H.HALLID
    JOIN CHBS_SLOTINFO S1 ON B.STARTSLOT = S1.SLOTID
    JOIN CHBS_SLOTINFO S2 ON B.ENDSLOT = S2.SLOTID
    LEFT JOIN CHBS_MEETINFO M ON B.BOOKINGID = M.BOOKINGID
    LEFT JOIN CHBS_MEETINGTYPES MT ON M.MEETTYPE = MT.MEETID
    WHERE B.BOOKINGSTATUS = 'PENDING'
    ORDER BY B.BOOKINGDATE ASC, S1.SLOTID ASC;
END //

-- USER CANCEL
CREATE PROCEDURE CHSP_BK_CNCL(IN p_BKID VARCHAR(50), IN p_EmpCode VARCHAR(7))
BEGIN
    DECLARE v_status VARCHAR(20);
    DECLARE v_owner VARCHAR(7);

    SELECT BOOKINGSTATUS, BOOKEDBY INTO v_status, v_owner
    FROM CHBS_BOOKINGINFO WHERE BOOKINGID = p_BKID;

    IF v_owner IS NULL THEN
        SELECT 'NOT_FOUND' AS Status;
    ELSEIF v_owner <> p_EmpCode THEN
        SELECT 'UNAUTHORIZED' AS Status;
    ELSEIF v_status NOT IN ('CONFIRMED', 'PENDING') THEN
        SELECT 'ALREADY_CLOSED' AS Status;
    ELSE
        UPDATE CHBS_BOOKINGINFO SET BOOKINGSTATUS = 'CANCELLED' WHERE BOOKINGID = p_BKID;
        SELECT 'SUCCESS' AS Status;
    END IF;
END //

DELIMITER ;


CREATE OR REPLACE VIEW VW_CHBS_DASHBOARD AS
SELECT 
    B.BOOKINGID,
    B.BOOKINGDATE     AS MeetDate,
    B.BOOKINGSTATUS,
    H.HALLNAME,
    H.BUILDNAME,
    H.ISDIRECTORHALL,
    CONCAT(S1.SLOTTIME, ' to ', S2.SLOTTIME) AS TIME_RANGE,
    M.MEETTITLE,
    MT.MEETNAME       AS MeetType,
    B.BOOKEDBY,
    B.ONBEHALFOF,
    B.CREATED_AT      AS TransactionTime
FROM CHBS_BOOKINGINFO B
JOIN  CHBS_HALLS       H  ON B.HALLID    = H.HALLID
JOIN  CHBS_SLOTINFO    S1 ON B.STARTSLOT = S1.SLOTID
JOIN  CHBS_SLOTINFO    S2 ON B.ENDSLOT   = S2.SLOTID
LEFT JOIN CHBS_MEETINFO      M  ON B.BOOKINGID = M.BOOKINGID
LEFT JOIN CHBS_MEETINGTYPES  MT ON M.MEETTYPE  = MT.MEETID
WHERE B.BOOKINGSTATUS IN ('CONFIRMED', 'PENDING');

CREATE OR REPLACE VIEW VW_CHBS_HISTORY AS
SELECT 
    BH.BOOKINGID,
    BH.BOOKINGDATE    AS MeetDate,
    BH.BOOKINGSTATUS,
    H.HALLNAME,
    H.BUILDNAME,
    H.ISDIRECTORHALL,
    CONCAT(S1.SLOTTIME, ' to ', S2.SLOTTIME) AS TIME_RANGE,
    MH.MEETTITLE,
    MT.MEETNAME       AS MeetType,
    BH.BOOKEDBY,
    BH.ONBEHALFOF,
    BH.CREATED_AT     AS TransactionTime
FROM CHBS_BK_HIST BH
JOIN  CHBS_HALLS       H  ON BH.HALLID    = H.HALLID
JOIN  CHBS_SLOTINFO    S1 ON BH.STARTSLOT = S1.SLOTID
JOIN  CHBS_SLOTINFO    S2 ON BH.ENDSLOT   = S2.SLOTID
LEFT JOIN CHBS_MT_HIST       MH ON BH.BOOKINGID = MH.BOOKINGID
LEFT JOIN CHBS_MEETINGTYPES  MT ON MH.MEETTYPE  = MT.MEETID;

DELIMITER //
CREATE PROCEDURE CHSP_GET_HOLDY()
BEGIN
    SELECT * FROM CHBS_HOLIDAYS;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE CHSP_GET_HOLS()
BEGIN
	SELECT HOLIDAYDATE, HOLIDAYNAME, HOLIDAYTYPE FROM CHBS_HOLIDAYS;
END//
DELIMITER ;

DROP PROCEDURE IF EXISTS CHSP_GET_AHAL;
DROP procedure IF EXISTS CHSP_GET_HOLDY;
DROP PROCEDURE IF EXISTS CHSP_HAL_ALL;


DELIMITER //
CREATE PROCEDURE CHSP_HAL_AVAIL(IN p_Date DATE)
BEGIN
    SELECT HALLID, HALLNAME, BUILDNAME, HALLCODE, ISDIRECTORHALL
    FROM CHBS_HALLS
    WHERE ISAVAILABLE = 1
      AND (
          DISABLED_FROM IS NULL                         
          OR p_Date NOT BETWEEN DISABLED_FROM AND DISABLED_TO  
      )
    ORDER BY BUILDNAME, HALLNAME;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE CHSP_HAL_ALL()
BEGIN
    SELECT HALLID, HALLNAME, BUILDNAME, HALLCODE, ISAVAILABLE, ISDIRECTORHALL,
           DISABLED_FROM, DISABLED_TO
    FROM CHBS_HALLS ORDER BY BUILDNAME, HALLNAME;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE CHSP_CHK_AVAIL(IN p_HallID INT, IN p_Date DATE, IN p_Start INT, IN p_End INT)
BEGIN
    SELECT COUNT(*) AS ConflictCount
    FROM CHBS_BOOKINGINFO
    WHERE HALLID = p_HallID
      AND BOOKINGDATE = p_Date
      AND BOOKINGSTATUS IN ('CONFIRMED', 'PENDING')
      AND STARTSLOT < p_End
      AND ENDSLOT > p_Start;
END //

DELIMITER ;

DELIMITER //
CREATE PROCEDURE CHSP_GET_HALB(IN p_MDate DATE)
BEGIN
    SELECT HALLID,HALLNAME,BUILDNAME,ISDIRECTORHALL FROM CHBS_HALLS
    WHERE ISAVAILABLE=1 OR NOT (DISABLED_FROM < p_MDate OR DISABLED_TO > p_MDate);
END //

DELIMITER ;

DELIMITER //



DELIMITER ;


DELIMITER //

CREATE PROCEDURE CHSP_BKDT(IN p_Date DATE)
BEGIN
    SELECT 
        B.BOOKINGID,
        B.HALLID,                          -- ← needed for row mapping
        H.HALLNAME,
        H.BUILDNAME,
        B.BOOKINGDATE AS MeetDate,
        B.BOOKINGSTATUS,
        B.STARTSLOT,                       -- ← numeric (1–32), for left position
        B.ENDSLOT,                         -- ← numeric (1–32), for width
        S1.SLOTTIME AS StartTime,          -- ← "09:00" string, for display only
        S2.SLOTTIME AS EndTime,            -- ← "10:00" string, for display only
        M.MEETTITLE,
        MT.MEETNAME AS MeetType,
        B.BOOKEDBY,
        B.ONBEHALFOF
    FROM CHBS_BOOKINGINFO B
    JOIN CHBS_HALLS H      ON B.HALLID    = H.HALLID
    JOIN CHBS_SLOTINFO S1  ON B.STARTSLOT = S1.SLOTID
    JOIN CHBS_SLOTINFO S2  ON B.ENDSLOT   = S2.SLOTID
    LEFT JOIN CHBS_MEETINFO M        ON B.BOOKINGID = M.BOOKINGID
    LEFT JOIN CHBS_MEETINGTYPES MT   ON M.MEETTYPE  = MT.MEETID
    WHERE B.BOOKINGDATE  = p_Date
      AND B.BOOKINGSTATUS = 'CONFIRMED'    -- ← strictly confirmed
    ORDER BY S1.SLOTID ASC, H.BUILDNAME ASC, H.HALLNAME ASC;
END //

DELIMITER ;

SET GLOBAL event_scheduler = ON;

CREATE EVENT IF NOT EXISTS EVT_DAILY_CHBS_MAINTENANCE
ON SCHEDULE EVERY 1 DAY
STARTS (TIMESTAMP(CURRENT_DATE) + INTERVAL 1 DAY)
DO CALL CHSP_AD_MAINTENANCE_AUTO();