-- 1. REFERENCE DATA
CREATE TABLE CHBS2_ROLEINFO (
    ROLEID VARCHAR(20) PRIMARY KEY, 
    ROLEDESC VARCHAR(100) NOT NULL
)
GO

CREATE TABLE CHBS2_SLOTINFO (
    SLOTID INT PRIMARY KEY, 
    SLOTTIME VARCHAR(30) NOT NULL
)
GO

CREATE TABLE CHBS2_MEETINGTYPES (
    MEETID INT IDENTITY PRIMARY KEY,
    MEETNAME VARCHAR(100) NOT NULL,
    MEETDESC VARCHAR(100) NOT NULL
)
GO

-- 2. ACCESS CONTROL & USERS
CREATE TABLE CHBS2_USERINFO (
    EMPLOYEECODE VARCHAR(7) PRIMARY KEY,
    EMPLOYEENAME VARCHAR(100) NOT NULL,
    PASSWRD VARCHAR(255) NOT NULL, 
    STATUS VARCHAR(10) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    ROLEID VARCHAR(20) NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES CHBS2_ROLEINFO (ROLEID)
)
GO

CREATE TABLE CHBS2_PA (
    PA_EMPCODE VARCHAR(7) PRIMARY KEY,
    PA_NAME VARCHAR(100) NOT NULL,
    PASSWRD VARCHAR(255) NOT NULL, 
    STATUS VARCHAR(10) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
)
GO

-- 3. FACILITY & HOLIDAYS
CREATE TABLE CHBS2_HALLS (
    HALLID INT IDENTITY PRIMARY KEY, 
    BUILDNAME VARCHAR(100) NOT NULL,
    HALLNAME VARCHAR(100) NOT NULL,
    HALLCODE VARCHAR(20) NOT NULL,
    ISAVAILABLE TINYINT DEFAULT 1,
    ISDIRECTORHALL TINYINT DEFAULT 0, 
    DISABLED_FROM DATE NULL,
    DISABLED_TO DATE NULL,
    CONSTRAINT UNQ_HALLCODE UNIQUE (HALLCODE)
)
GO

CREATE TABLE CHBS2_HOLIDAYS (
    HOLIDAYDATE DATE PRIMARY KEY,
    HOLIDAYNAME VARCHAR(100) NOT NULL,
    HOLIDAYTYPE VARCHAR(20) DEFAULT 'NATIONAL',
    ISRECURRING BIT DEFAULT 0
)
GO

-- 4. TRANSACTIONAL CORE
CREATE TABLE CHBS2_BOOKINGINFO (
    BOOKINGID VARCHAR(50) PRIMARY KEY,
    HALLID INT NOT NULL,
    BOOKEDBY VARCHAR(7) NOT NULL,
    ONBEHALFOF VARCHAR(7) NULL,
    STARTSLOT INT NOT NULL,
    ENDSLOT INT NOT NULL,
    BOOKINGDATE DATE NOT NULL,
    BOOKINGSTATUS VARCHAR(10) DEFAULT 'CONFIRMED' CHECK (BOOKINGSTATUS IN ('CONFIRMED', 'PENDING', 'CANCELLED', 'REJECTED')),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_BI_HALL FOREIGN KEY (HALLID) REFERENCES CHBS2_HALLS (HALLID),
    CONSTRAINT FK_BI_SLOT_START FOREIGN KEY (STARTSLOT) REFERENCES CHBS2_SLOTINFO (SLOTID),
    CONSTRAINT FK_BI_SLOT_END FOREIGN KEY (ENDSLOT) REFERENCES CHBS2_SLOTINFO (SLOTID)
)
GO

CREATE TABLE CHBS2_MEETINFO (
    BOOKINGID VARCHAR(50) PRIMARY KEY,
    MEETTITLE VARCHAR(150) NOT NULL,
    MEETTYPE INT NOT NULL,
    LINKREQUIRED VARCHAR(3) DEFAULT 'NO' CHECK (LINKREQUIRED IN ('YES', 'NO')),
    CONSTRAINT FK_MI_BOOKING FOREIGN KEY (BOOKINGID) REFERENCES CHBS2_BOOKINGINFO (BOOKINGID),
    CONSTRAINT FK_MI_MTYP FOREIGN KEY (MEETTYPE) REFERENCES CHBS2_MEETINGTYPES (MEETID)
)
GO

-- 5. HISTORY TABLES (Manual copy of schema as LIKE is not supported)
CREATE TABLE CHBS2_BK_HIST (
    BOOKINGID VARCHAR(50) PRIMARY KEY,
    HALLID INT NOT NULL,
    BOOKEDBY VARCHAR(7) NOT NULL,
    ONBEHALFOF VARCHAR(7) NULL,
    STARTSLOT INT NOT NULL,
    ENDSLOT INT NOT NULL,
    BOOKINGDATE DATE NOT NULL,
    BOOKINGSTATUS VARCHAR(10),
    CREATED_AT DATETIME
)
GO

CREATE TABLE CHBS2_MT_HIST (
    BOOKINGID VARCHAR(50) PRIMARY KEY,
    MEETTITLE VARCHAR(150) NOT NULL,
    MEETTYPE INT NOT NULL,
    LINKREQUIRED VARCHAR(3)
)
GO